version: '3'

services:

    whatthefinances:
        build: whatthefinances
        volumes:
            - ./whatthefinances/config.json:/whatthefinances/config.json
            - ./whatthefinances/entrypoint.sh:/whatthefinances/entrypoint.sh
            - ./whatthefinances/database.sqlite3:/whatthefinances/database.sqlite3
        container_name: whatthefinances
        ports:
             - "9090:9090/tcp"
        networks:
            - whatthefinances-net

networks:
  whatthefinances-net:

